apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commons
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kiowy-org/k8s-lab.git
    targetRevision: HEAD
    path: 5_argo_cd/common