# Simplified template
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: errors
  namespace: argocd
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/kiowy-org/k8s-ckad-lab.git  # Git Reposition URL
    targetRevision: HEAD  # Keep Helm
    path: .to_fix

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: true 
