apiVersion: batch/v1
kind: CronJob
metadata:
  name: unlock
  namespace: default
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: try-unlock
            image: alpine/curl:3.14
            imagePullPolicy: IfNotPresent 
            command: ["curl"] 
            args: ["what-an-url.default:8080 -d unlocker=default"]
          restartPolicy: Never