apiVersion: apps/v1
kind: Deployment
metadata:
  name: door
  namespace: default
spec:
  selector:
    matchLabels:
      app-of: default
  replicas: 1
  template:
    metadata:
      labels:
        app-of: default
    spec:
      containers:
      - name: the-door
        image: europe-west1-docker.pkg.dev/k8s-formation/formation-img/unlocker:1.6
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
        env:
        - name: OWNER_NAME
          valueFrom:
            configMapKeyRef:
              name: default-cm
              key: owner_name
      - name: busybox
        image: busybox
        args:
        - sleep
        - "1000"
      
