apiVersion: v1
kind: Service
metadata:
  name: what-an-url
  namespace: default
spec:
  type: ClusterIP
  selector:
    app-of: default
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
